export * from './auth-controller.service';
import { AuthControllerService } from './auth-controller.service';
export * from './communes-controller.service';
import { CommunesControllerService } from './communes-controller.service';
export * from './contrats-controller.service';
import { ContratsControllerService } from './contrats-controller.service';
export * from './dashboard-events-internes-controller.service';
import { DashboardEventsInternesControllerService } from './dashboard-events-internes-controller.service';
export * from './evenements-controller.service';
import { EvenementsControllerService } from './evenements-controller.service';
export * from './job-controller.service';
import { JobControllerService } from './job-controller.service';
export * from './matieres-controller.service';
import { MatieresControllerService } from './matieres-controller.service';
export * from './mot-de-passe-controller.service';
import { MotDePasseControllerService } from './mot-de-passe-controller.service';
export * from './motifs-liste-noire-controller.service';
import { MotifsListeNoireControllerService } from './motifs-liste-noire-controller.service';
export * from './moyens-paiements-controller.service';
import { MoyensPaiementsControllerService } from './moyens-paiements-controller.service';
export * from './smartphones-controller.service';
import { SmartphonesControllerService } from './smartphones-controller.service';
export * from './types-apporteurs-controller.service';
import { TypesApporteursControllerService } from './types-apporteurs-controller.service';
export * from './unites-des-apports-controller.service';
import { UnitesDesApportsControllerService } from './unites-des-apports-controller.service';
export * from './usagers-controller.service';
import { UsagersControllerService } from './usagers-controller.service';
export * from './utilisateurs-sites-controller.service';
import { UtilisateursSitesControllerService } from './utilisateurs-sites-controller.service';
export const APIS = [AuthControllerService, CommunesControllerService, ContratsControllerService, DashboardEventsInternesControllerService, EvenementsControllerService, JobControllerService, MatieresControllerService, MotDePasseControllerService, MotifsListeNoireControllerService, MoyensPaiementsControllerService, SmartphonesControllerService, TypesApporteursControllerService, UnitesDesApportsControllerService, UsagersControllerService, UtilisateursSitesControllerService];
