export * from './auth-controller.service';
import { AuthControllerService } from './auth-controller.service';
export * from './contrat-controller.service';
import { ContratControllerService } from './contrat-controller.service';
export * from './dechetterie-controller.service';
import { DechetterieControllerService } from './dechetterie-controller.service';
export * from './demande-inscription-controller.service';
import { DemandeInscriptionControllerService } from './demande-inscription-controller.service';
export * from './inscription-controller.service';
import { InscriptionControllerService } from './inscription-controller.service';
export * from './mot-de-passe-controller.service';
import { MotDePasseControllerService } from './mot-de-passe-controller.service';
export * from './usager-controller.service';
import { UsagerControllerService } from './usager-controller.service';
export * from './vehicule-controller.service';
import { VehiculeControllerService } from './vehicule-controller.service';
export const APIS = [AuthControllerService, ContratControllerService, DechetterieControllerService, DemandeInscriptionControllerService, InscriptionControllerService, MotDePasseControllerService, UsagerControllerService, VehiculeControllerService];
