/**
 * API (idbatv7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec, HttpContext 
        }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';


// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { BaseService } from '../api.base.service';



@Injectable({
  providedIn: 'root'
})
export class InscriptionControllerService extends BaseService {

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string|string[], @Optional() configuration?: Configuration) {
        super(basePath, configuration);
    }

    /**
     * @endpoint post /api/inscription
     * @param type 
     * @param contratUrl 
     * @param nom 
     * @param prenom 
     * @param adresse 
     * @param ville 
     * @param courriel 
     * @param telephone 
     * @param cartePhysique 
     * @param carteDematerialisee 
     * @param mentionsLegales 
     * @param deuxiemeNom 
     * @param deuxiemePrenom 
     * @param complementAdresse 
     * @param societe 
     * @param siret 
     * @param immatriculation 
     * @param zoneJ1 
     * @param zoneF3 
     * @param codePostal 
     * @param carteIdentite 
     * @param justificatifDomicile 
     * @param carteGrise 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public inscrire(type: string, contratUrl: string, nom: string, prenom: string, adresse: string, ville: string, courriel: string, telephone: string, cartePhysique: boolean, carteDematerialisee: boolean, mentionsLegales: boolean, deuxiemeNom?: string, deuxiemePrenom?: string, complementAdresse?: string, societe?: string, siret?: string, immatriculation?: string, zoneJ1?: string, zoneF3?: number, codePostal?: string, carteIdentite?: Blob, justificatifDomicile?: Blob, carteGrise?: Blob, observe?: 'body', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<any>;
    public inscrire(type: string, contratUrl: string, nom: string, prenom: string, adresse: string, ville: string, courriel: string, telephone: string, cartePhysique: boolean, carteDematerialisee: boolean, mentionsLegales: boolean, deuxiemeNom?: string, deuxiemePrenom?: string, complementAdresse?: string, societe?: string, siret?: string, immatriculation?: string, zoneJ1?: string, zoneF3?: number, codePostal?: string, carteIdentite?: Blob, justificatifDomicile?: Blob, carteGrise?: Blob, observe?: 'response', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<HttpResponse<any>>;
    public inscrire(type: string, contratUrl: string, nom: string, prenom: string, adresse: string, ville: string, courriel: string, telephone: string, cartePhysique: boolean, carteDematerialisee: boolean, mentionsLegales: boolean, deuxiemeNom?: string, deuxiemePrenom?: string, complementAdresse?: string, societe?: string, siret?: string, immatriculation?: string, zoneJ1?: string, zoneF3?: number, codePostal?: string, carteIdentite?: Blob, justificatifDomicile?: Blob, carteGrise?: Blob, observe?: 'events', reportProgress?: boolean, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<HttpEvent<any>>;
    public inscrire(type: string, contratUrl: string, nom: string, prenom: string, adresse: string, ville: string, courriel: string, telephone: string, cartePhysique: boolean, carteDematerialisee: boolean, mentionsLegales: boolean, deuxiemeNom?: string, deuxiemePrenom?: string, complementAdresse?: string, societe?: string, siret?: string, immatriculation?: string, zoneJ1?: string, zoneF3?: number, codePostal?: string, carteIdentite?: Blob, justificatifDomicile?: Blob, carteGrise?: Blob, observe: any = 'body', reportProgress: boolean = false, options?: {httpHeaderAccept?: undefined, context?: HttpContext, transferCache?: boolean}): Observable<any> {
        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling inscrire.');
        }
        if (contratUrl === null || contratUrl === undefined) {
            throw new Error('Required parameter contratUrl was null or undefined when calling inscrire.');
        }
        if (nom === null || nom === undefined) {
            throw new Error('Required parameter nom was null or undefined when calling inscrire.');
        }
        if (prenom === null || prenom === undefined) {
            throw new Error('Required parameter prenom was null or undefined when calling inscrire.');
        }
        if (adresse === null || adresse === undefined) {
            throw new Error('Required parameter adresse was null or undefined when calling inscrire.');
        }
        if (ville === null || ville === undefined) {
            throw new Error('Required parameter ville was null or undefined when calling inscrire.');
        }
        if (courriel === null || courriel === undefined) {
            throw new Error('Required parameter courriel was null or undefined when calling inscrire.');
        }
        if (telephone === null || telephone === undefined) {
            throw new Error('Required parameter telephone was null or undefined when calling inscrire.');
        }
        if (cartePhysique === null || cartePhysique === undefined) {
            throw new Error('Required parameter cartePhysique was null or undefined when calling inscrire.');
        }
        if (carteDematerialisee === null || carteDematerialisee === undefined) {
            throw new Error('Required parameter carteDematerialisee was null or undefined when calling inscrire.');
        }
        if (mentionsLegales === null || mentionsLegales === undefined) {
            throw new Error('Required parameter mentionsLegales was null or undefined when calling inscrire.');
        }

        let localVarQueryParameters = new HttpParams({encoder: this.encoder});
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>type, 'type');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>contratUrl, 'contratUrl');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>nom, 'nom');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>prenom, 'prenom');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>adresse, 'adresse');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>ville, 'ville');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>courriel, 'courriel');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>telephone, 'telephone');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>cartePhysique, 'cartePhysique');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>carteDematerialisee, 'carteDematerialisee');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>mentionsLegales, 'mentionsLegales');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>deuxiemeNom, 'deuxiemeNom');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>deuxiemePrenom, 'deuxiemePrenom');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>complementAdresse, 'complementAdresse');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>societe, 'societe');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>siret, 'siret');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>immatriculation, 'immatriculation');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>zoneJ1, 'zoneJ1');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>zoneF3, 'zoneF3');
        localVarQueryParameters = this.addToHttpParams(localVarQueryParameters,
          <any>codePostal, 'codePostal');

        let localVarHeaders = this.defaultHeaders;

        // authentication (bearerAuth) required
        localVarHeaders = this.configuration.addCredentialToHeaders('bearerAuth', 'Authorization', localVarHeaders, 'Bearer ');

        const localVarHttpHeaderAcceptSelected: string | undefined = options?.httpHeaderAccept ?? this.configuration.selectHeaderAccept([
        ]);
        if (localVarHttpHeaderAcceptSelected !== undefined) {
            localVarHeaders = localVarHeaders.set('Accept', localVarHttpHeaderAcceptSelected);
        }

        const localVarHttpContext: HttpContext = options?.context ?? new HttpContext();

        const localVarTransferCache: boolean = options?.transferCache ?? true;

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let localVarFormParams: { append(param: string, value: any): any; };
        let localVarUseForm = false;
        let localVarConvertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        localVarUseForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        localVarUseForm = canConsumeForm;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        localVarUseForm = canConsumeForm;
        if (localVarUseForm) {
            localVarFormParams = new FormData();
        } else {
            localVarFormParams = new HttpParams({encoder: this.encoder});
        }

        if (carteIdentite !== undefined) {
            localVarFormParams = localVarFormParams.append('carteIdentite', <any>carteIdentite) as any || localVarFormParams;
        }
        if (justificatifDomicile !== undefined) {
            localVarFormParams = localVarFormParams.append('justificatifDomicile', <any>justificatifDomicile) as any || localVarFormParams;
        }
        if (carteGrise !== undefined) {
            localVarFormParams = localVarFormParams.append('carteGrise', <any>carteGrise) as any || localVarFormParams;
        }

        let responseType_: 'text' | 'json' | 'blob' = 'json';
        if (localVarHttpHeaderAcceptSelected) {
            if (localVarHttpHeaderAcceptSelected.startsWith('text')) {
                responseType_ = 'text';
            } else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
                responseType_ = 'json';
            } else {
                responseType_ = 'blob';
            }
        }

        let localVarPath = `/api/inscription`;
        const { basePath, withCredentials } = this.configuration;
        return this.httpClient.request<any>('post', `${basePath}${localVarPath}`,
            {
                context: localVarHttpContext,
                body: localVarConvertFormParamsToString ? localVarFormParams.toString() : localVarFormParams,
                params: localVarQueryParameters,
                responseType: <any>responseType_,
                ...(withCredentials ? { withCredentials } : {}),
                headers: localVarHeaders,
                observe: observe,
                ...(localVarTransferCache !== undefined ? { transferCache: localVarTransferCache } : {}),
                reportProgress: reportProgress
            }
        );
    }

}
