//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srPayFip
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
        "ement_securise/PaiementSecuriseService")]
    public partial class FonctionnelleErreur
    {
        
        private string codeField;
        
        private string descriptifField;
        
        private string libelleField;
        
        private string messageField;
        
        private int severiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descriptif
        {
            get
            {
                return this.descriptifField;
            }
            set
            {
                this.descriptifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string libelle
        {
            get
            {
                return this.libelleField;
            }
            set
            {
                this.libelleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int severite
        {
            get
            {
                return this.severiteField;
            }
            set
            {
                this.severiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/reponse")]
    public partial class CreerPaiementSecuriseResponse
    {
        
        private string idOpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idOp
        {
            get
            {
                return this.idOpField;
            }
            set
            {
                this.idOpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/requete")]
    public partial class CreerPaiementSecuriseRequest
    {
        
        private string exerField;
        
        private string melField;
        
        private string montantField;
        
        private string numcliField;
        
        private string objetField;
        
        private string refdetField;
        
        private string saisieField;
        
        private string urlnotifField;
        
        private string urlredirectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string exer
        {
            get
            {
                return this.exerField;
            }
            set
            {
                this.exerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mel
        {
            get
            {
                return this.melField;
            }
            set
            {
                this.melField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string montant
        {
            get
            {
                return this.montantField;
            }
            set
            {
                this.montantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numcli
        {
            get
            {
                return this.numcliField;
            }
            set
            {
                this.numcliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string objet
        {
            get
            {
                return this.objetField;
            }
            set
            {
                this.objetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string refdet
        {
            get
            {
                return this.refdetField;
            }
            set
            {
                this.refdetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string saisie
        {
            get
            {
                return this.saisieField;
            }
            set
            {
                this.saisieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string urlnotif
        {
            get
            {
                return this.urlnotifField;
            }
            set
            {
                this.urlnotifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string urlredirect
        {
            get
            {
                return this.urlredirectField;
            }
            set
            {
                this.urlredirectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
        "ement_securise/PaiementSecuriseService")]
    public partial class TechDysfonctionnementErreur
    {
        
        private string codeField;
        
        private string descriptifField;
        
        private string libelleField;
        
        private string messageField;
        
        private int severiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descriptif
        {
            get
            {
                return this.descriptifField;
            }
            set
            {
                this.descriptifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string libelle
        {
            get
            {
                return this.libelleField;
            }
            set
            {
                this.libelleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int severite
        {
            get
            {
                return this.severiteField;
            }
            set
            {
                this.severiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
        "ement_securise/PaiementSecuriseService")]
    public partial class TechIndisponibiliteErreur
    {
        
        private string codeField;
        
        private string descriptifField;
        
        private string libelleField;
        
        private string messageField;
        
        private int severiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descriptif
        {
            get
            {
                return this.descriptifField;
            }
            set
            {
                this.descriptifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string libelle
        {
            get
            {
                return this.libelleField;
            }
            set
            {
                this.libelleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int severite
        {
            get
            {
                return this.severiteField;
            }
            set
            {
                this.severiteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
        "ement_securise/PaiementSecuriseService")]
    public partial class TechProtocolaireErreur
    {
        
        private string codeField;
        
        private string descriptifField;
        
        private string libelleField;
        
        private string messageField;
        
        private int severiteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descriptif
        {
            get
            {
                return this.descriptifField;
            }
            set
            {
                this.descriptifField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string libelle
        {
            get
            {
                return this.libelleField;
            }
            set
            {
                this.libelleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int severite
        {
            get
            {
                return this.severiteField;
            }
            set
            {
                this.severiteField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
        "ement_securise/PaiementSecuriseService", ConfigurationName="srPayFip.PaiementSecuriseService")]
    public interface PaiementSecuriseService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(srPayFip.FonctionnelleErreur), Action="", Name="FonctionnelleErreur")]
        [System.ServiceModel.FaultContractAttribute(typeof(srPayFip.TechDysfonctionnementErreur), Action="", Name="TechDysfonctionnementErreur")]
        [System.ServiceModel.FaultContractAttribute(typeof(srPayFip.TechIndisponibiliteErreur), Action="", Name="TechIndisponibiliteErreur")]
        [System.ServiceModel.FaultContractAttribute(typeof(srPayFip.TechProtocolaireErreur), Action="", Name="TechProtocolaireErreur")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<srPayFip.creerPaiementSecuriseResponse1> creerPaiementSecuriseAsync(srPayFip.creerPaiementSecuriseRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(srPayFip.FonctionnelleErreur), Action="", Name="FonctionnelleErreur")]
        [System.ServiceModel.FaultContractAttribute(typeof(srPayFip.TechDysfonctionnementErreur), Action="", Name="TechDysfonctionnementErreur")]
        [System.ServiceModel.FaultContractAttribute(typeof(srPayFip.TechIndisponibiliteErreur), Action="", Name="TechIndisponibiliteErreur")]
        [System.ServiceModel.FaultContractAttribute(typeof(srPayFip.TechProtocolaireErreur), Action="", Name="TechProtocolaireErreur")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<srPayFip.recupererDetailPaiementSecuriseResponse1> recupererDetailPaiementSecuriseAsync(srPayFip.recupererDetailPaiementSecuriseRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(srPayFip.FonctionnelleErreur), Action="", Name="FonctionnelleErreur")]
        [System.ServiceModel.FaultContractAttribute(typeof(srPayFip.TechDysfonctionnementErreur), Action="", Name="TechDysfonctionnementErreur")]
        [System.ServiceModel.FaultContractAttribute(typeof(srPayFip.TechIndisponibiliteErreur), Action="", Name="TechIndisponibiliteErreur")]
        [System.ServiceModel.FaultContractAttribute(typeof(srPayFip.TechProtocolaireErreur), Action="", Name="TechProtocolaireErreur")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<srPayFip.recupererDetailClientResponse1> recupererDetailClientAsync(srPayFip.recupererDetailClientRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="creerPaiementSecurise", WrapperNamespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
        "ement_securise/PaiementSecuriseService", IsWrapped=true)]
    public partial class creerPaiementSecuriseRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
            "ement_securise/PaiementSecuriseService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srPayFip.CreerPaiementSecuriseRequest arg0;
        
        public creerPaiementSecuriseRequest1()
        {
        }
        
        public creerPaiementSecuriseRequest1(srPayFip.CreerPaiementSecuriseRequest arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="creerPaiementSecuriseResponse", WrapperNamespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
        "ement_securise/PaiementSecuriseService", IsWrapped=true)]
    public partial class creerPaiementSecuriseResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
            "ement_securise/PaiementSecuriseService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srPayFip.CreerPaiementSecuriseResponse @return;
        
        public creerPaiementSecuriseResponse1()
        {
        }
        
        public creerPaiementSecuriseResponse1(srPayFip.CreerPaiementSecuriseResponse @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/reponse")]
    public partial class RecupererDetailPaiementSecuriseRequest
    {
        
        private string idOpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idOp
        {
            get
            {
                return this.idOpField;
            }
            set
            {
                this.idOpField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/reponse")]
    public partial class RecupererDetailPaiementSecuriseResponse
    {
        
        private string dattransField;
        
        private string exerField;
        
        private string heurtransField;
        
        private string idOpField;
        
        private string melField;
        
        private string montantField;
        
        private string numautoField;
        
        private string numcliField;
        
        private string objetField;
        
        private string refdetField;
        
        private string resultransField;
        
        private string saisieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dattrans
        {
            get
            {
                return this.dattransField;
            }
            set
            {
                this.dattransField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string exer
        {
            get
            {
                return this.exerField;
            }
            set
            {
                this.exerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string heurtrans
        {
            get
            {
                return this.heurtransField;
            }
            set
            {
                this.heurtransField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string idOp
        {
            get
            {
                return this.idOpField;
            }
            set
            {
                this.idOpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string mel
        {
            get
            {
                return this.melField;
            }
            set
            {
                this.melField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string montant
        {
            get
            {
                return this.montantField;
            }
            set
            {
                this.montantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string numauto
        {
            get
            {
                return this.numautoField;
            }
            set
            {
                this.numautoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string numcli
        {
            get
            {
                return this.numcliField;
            }
            set
            {
                this.numcliField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string objet
        {
            get
            {
                return this.objetField;
            }
            set
            {
                this.objetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string refdet
        {
            get
            {
                return this.refdetField;
            }
            set
            {
                this.refdetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string resultrans
        {
            get
            {
                return this.resultransField;
            }
            set
            {
                this.resultransField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string saisie
        {
            get
            {
                return this.saisieField;
            }
            set
            {
                this.saisieField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recupererDetailPaiementSecurise", WrapperNamespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
        "ement_securise/PaiementSecuriseService", IsWrapped=true)]
    public partial class recupererDetailPaiementSecuriseRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
            "ement_securise/PaiementSecuriseService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srPayFip.RecupererDetailPaiementSecuriseRequest arg0;
        
        public recupererDetailPaiementSecuriseRequest1()
        {
        }
        
        public recupererDetailPaiementSecuriseRequest1(srPayFip.RecupererDetailPaiementSecuriseRequest arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recupererDetailPaiementSecuriseResponse", WrapperNamespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
        "ement_securise/PaiementSecuriseService", IsWrapped=true)]
    public partial class recupererDetailPaiementSecuriseResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
            "ement_securise/PaiementSecuriseService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srPayFip.RecupererDetailPaiementSecuriseResponse @return;
        
        public recupererDetailPaiementSecuriseResponse1()
        {
        }
        
        public recupererDetailPaiementSecuriseResponse1(srPayFip.RecupererDetailPaiementSecuriseResponse @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/reponse")]
    public partial class RecupererDetailClientRequest
    {
        
        private string numCliField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numCli
        {
            get
            {
                return this.numCliField;
            }
            set
            {
                this.numCliField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/reponse")]
    public partial class RecupererDetailClientResponse
    {
        
        private string libelleN1Field;
        
        private string libelleN2Field;
        
        private string libelleN3Field;
        
        private string numcliField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string libelleN1
        {
            get
            {
                return this.libelleN1Field;
            }
            set
            {
                this.libelleN1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string libelleN2
        {
            get
            {
                return this.libelleN2Field;
            }
            set
            {
                this.libelleN2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string libelleN3
        {
            get
            {
                return this.libelleN3Field;
            }
            set
            {
                this.libelleN3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string numcli
        {
            get
            {
                return this.numcliField;
            }
            set
            {
                this.numcliField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recupererDetailClient", WrapperNamespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
        "ement_securise/PaiementSecuriseService", IsWrapped=true)]
    public partial class recupererDetailClientRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
            "ement_securise/PaiementSecuriseService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srPayFip.RecupererDetailClientRequest arg0;
        
        public recupererDetailClientRequest1()
        {
        }
        
        public recupererDetailClientRequest1(srPayFip.RecupererDetailClientRequest arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="recupererDetailClientResponse", WrapperNamespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
        "ement_securise/PaiementSecuriseService", IsWrapped=true)]
    public partial class recupererDetailClientResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://securite.service.tpa.cp.finances.gouv.fr/services/mas_securite/contrat_pai" +
            "ement_securise/PaiementSecuriseService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public srPayFip.RecupererDetailClientResponse @return;
        
        public recupererDetailClientResponse1()
        {
        }
        
        public recupererDetailClientResponse1(srPayFip.RecupererDetailClientResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface PaiementSecuriseServiceChannel : srPayFip.PaiementSecuriseService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class PaiementSecuriseServiceClient : System.ServiceModel.ClientBase<srPayFip.PaiementSecuriseService>, srPayFip.PaiementSecuriseService
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public PaiementSecuriseServiceClient() : 
                base(PaiementSecuriseServiceClient.GetDefaultBinding(), PaiementSecuriseServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.PaiementSecuriseServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaiementSecuriseServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(PaiementSecuriseServiceClient.GetBindingForEndpoint(endpointConfiguration), PaiementSecuriseServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaiementSecuriseServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(PaiementSecuriseServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaiementSecuriseServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(PaiementSecuriseServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public PaiementSecuriseServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srPayFip.creerPaiementSecuriseResponse1> srPayFip.PaiementSecuriseService.creerPaiementSecuriseAsync(srPayFip.creerPaiementSecuriseRequest1 request)
        {
            return base.Channel.creerPaiementSecuriseAsync(request);
        }
        
        public System.Threading.Tasks.Task<srPayFip.creerPaiementSecuriseResponse1> creerPaiementSecuriseAsync(srPayFip.CreerPaiementSecuriseRequest arg0)
        {
            srPayFip.creerPaiementSecuriseRequest1 inValue = new srPayFip.creerPaiementSecuriseRequest1();
            inValue.arg0 = arg0;
            return ((srPayFip.PaiementSecuriseService)(this)).creerPaiementSecuriseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srPayFip.recupererDetailPaiementSecuriseResponse1> srPayFip.PaiementSecuriseService.recupererDetailPaiementSecuriseAsync(srPayFip.recupererDetailPaiementSecuriseRequest1 request)
        {
            return base.Channel.recupererDetailPaiementSecuriseAsync(request);
        }
        
        public System.Threading.Tasks.Task<srPayFip.recupererDetailPaiementSecuriseResponse1> recupererDetailPaiementSecuriseAsync(srPayFip.RecupererDetailPaiementSecuriseRequest arg0)
        {
            srPayFip.recupererDetailPaiementSecuriseRequest1 inValue = new srPayFip.recupererDetailPaiementSecuriseRequest1();
            inValue.arg0 = arg0;
            return ((srPayFip.PaiementSecuriseService)(this)).recupererDetailPaiementSecuriseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srPayFip.recupererDetailClientResponse1> srPayFip.PaiementSecuriseService.recupererDetailClientAsync(srPayFip.recupererDetailClientRequest1 request)
        {
            return base.Channel.recupererDetailClientAsync(request);
        }
        
        public System.Threading.Tasks.Task<srPayFip.recupererDetailClientResponse1> recupererDetailClientAsync(srPayFip.RecupererDetailClientRequest arg0)
        {
            srPayFip.recupererDetailClientRequest1 inValue = new srPayFip.recupererDetailClientRequest1();
            inValue.arg0 = arg0;
            return ((srPayFip.PaiementSecuriseService)(this)).recupererDetailClientAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PaiementSecuriseServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                //result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.None;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.PaiementSecuriseServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://www.tipi-client.budget.gouv.fr:80/tpa/services/securite");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return PaiementSecuriseServiceClient.GetBindingForEndpoint(EndpointConfiguration.PaiementSecuriseServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return PaiementSecuriseServiceClient.GetEndpointAddress(EndpointConfiguration.PaiementSecuriseServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            PaiementSecuriseServicePort,
        }
    }
}
