export const routesConstantes = {
  home: 'home',
  login: 'connexion',
  motDePasseOublie: 'mot-de-passe-oublie',
  connexionIdemat: 'connexion-idemat',
  carteAcces: 'carte-acces',
  dechetteries: 'dechetteries',
  dechetterieDetail: 'dechetteries/:id',
  consultationSolde: 'consultation-solde',
  achatPassages: 'achat-passages',
  informationsPersonnelles: 'informations-personnelles',
  modificationProfil: 'modification-profil',
  parametresCompte: 'parametres-compte',
  modificationEmail: 'modification-email',
  modificationMotDePasseIdemat: 'modification-mot-de-passe',
  mentionsLegales: 'mentions-legales',
  creationCompte: 'creation-compte',
  demandeOk: 'demande-ok',
  nouveauMotDePasse: 'nouveau-mot-de-passe',
  mesDepots: 'mes-depots',
}
