export const routesConstantes = {
  home: 'home',
  login: 'connexion',
  motDePasseOublie: 'mot-de-passe-oublie',

  // --- ROUTES IDEMAT (portail usager) ---
  connexionIdemat: 'connexion-idemat',
  carteAcces: 'carte-acces',
  dechetteries: 'dechetteries',
  dechetterieDetail: 'dechetteries/:id',
  consultationSolde: 'consultation-solde',
  achatPassages: 'achat-passages',
  informationsPersonnelles: 'informations-personnelles',
  modificationProfil: 'modification-profil',
  parametresCompte: 'parametres-compte',
  modificationEmail: 'modification-email',
  modificationMotDePasseIdemat: 'modification-mot-de-passe',
  mentionsLegales: 'mentions-legales',
  creationCompte: 'creation-compte',
  demandeOk: 'demande-ok',
  listTypesApporteurs: 'types-apporteurs',
  addOrUpdateTypesApporteurs: 'types-apporteurs/add-or-update',
  listContrats: 'contrats',
  addOrUpdateContrat: 'contrats/add-or-update',
  listCommunes: 'communes',
  addOrUpdateCommune: 'communes/add-or-update',
  listMoyensPaiements: 'moyens-paiements',
  addOrUpdateMoyenPaiement: 'moyens-paiements/add-or-update',
  listMotifsListeNoire: 'motifs-liste-noire',
  addOrUpdateMotifListeNoire: 'motifs-liste-noire/add-or-update',
  listSignalements: 'signalements',
  addOrUpdateSignalement: 'signalements/add-or-update',
  listMatieres: 'matieres',
  addOrUpdateMatiere: 'matieres/add-or-update',
  listSitesContrats: 'sites-contrats',
  addOrUpdateSiteContrats: 'sites-contrats/add-or-update',
  listUnitesDesApports: 'unites-des-apports',
  addOrUpdateUniteDesApports: 'unites-des-apports/add-or-update',
  listEvenements: 'evenements',
  addOrUpdateEvenement: 'evenements/add-or-update',
  listSmartphones: 'smartphones',
  addOrUpdateSmartphone: 'smartphones/add-or-update',
  addOrUpdateUtilisateurSite: 'utilisateurs-sites/add-or-update',
}
