/**
 * API (idbatv7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommuneDio } from './commune-dio';


export interface ContratDio { 
    id: number;
    urlIdemat: string;
    nom: string;
    logoBase64?: string;
    logoMime?: string;
    communes: Array<CommuneDio>;
    allowCartePhysique: boolean;
    allowCarteDematerialisee: boolean;
    allowImmatriculations: boolean;
    demandeZoneJ1F3: boolean;
    allowAchatPassages: boolean;
    mentionsLegales?: string;
}

