/**
 * API (IDBATV7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContratTypeApporteurDto } from './contrat-type-apporteur-dto';
import { ContratCommuneDto } from './contrat-commune-dto';
import { ContratMatiereDto } from './contrat-matiere-dto';
import { ContratEvenementDto } from './contrat-evenement-dto';
import { ContratMotifListeNoireDto } from './contrat-motif-liste-noire-dto';
import { ContratMoyenPaiementDto } from './contrat-moyen-paiement-dto';


export interface ContratDto { 
    id: number;
    trigramme: string;
    nom: string;
    typesApporteurs: Array<ContratTypeApporteurDto>;
    communes: Array<ContratCommuneDto>;
    motifsListeNoires: Array<ContratMotifListeNoireDto>;
    moyensPaiements: Array<ContratMoyenPaiementDto>;
    matieres: Array<ContratMatiereDto>;
    evenements: Array<ContratEvenementDto>;
}

