/**
 * API (IDBATV7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UtilisateurSiteDto } from './utilisateur-site-dto';


export interface ContratFullDto { 
    id: number;
    trigramme: string;
    nom: string;
    utilsateurSites: Array<UtilisateurSiteDto>;
}

