/**
 * API (idbatv7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DechetterieDetailDio { 
    id: number;
    nom: string;
    adresse: string;
    codePostal: string;
    ville: string;
    horaires?: string;
}

