/**
 * API (IDBATV7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EventInterneDto { 
    id: number;
    statut: EventInterneDto.StatutEnum;
    code: EventInterneDto.CodeEnum;
    message?: string;
    dateCrea: string;
    tentativeCount: number;
}
export namespace EventInterneDto {
    export const StatutEnum = {
        EnAttente: 'EnAttente',
        EnCoursPlanification: 'EnCoursPlanification',
        Erreur: 'Erreur',
        Planifie: 'Planifie',
        RePlanifie: 'RePlanifie',
        Succes: 'Succes',
        EnCours: 'EnCours',
        Supprime: 'Supprime'
    } as const;
    export type StatutEnum = typeof StatutEnum[keyof typeof StatutEnum];
    export const CodeEnum = {
        EnvoisMail: 'EnvoisMail',
        CleanRateLimit: 'CleanRateLimit'
    } as const;
    export type CodeEnum = typeof CodeEnum[keyof typeof CodeEnum];
}


