/**
 * API (idbatv7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FichierDio } from './fichier-dio';
import { VehiculeInscriptionDioRequest } from './vehicule-inscription-dio-request';


export interface InscriptionDioRequest { 
    type: string;
    contratUrl: string;
    nom: string;
    prenom: string;
    adresse: string;
    communeContratId: number;
    courriel: string;
    telephone: string;
    cartePhysique: boolean;
    mentionsLegales: boolean;
    deuxiemeNom?: string;
    deuxiemePrenom?: string;
    complementAdresse?: string;
    societe?: string;
    siret?: string;
    vehicules?: Array<VehiculeInscriptionDioRequest>;
    carteIdentite?: FichierDio;
    justificatifDomicile?: FichierDio;
    kbis?: FichierDio;
}

