/**
 * API (idbatv7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModifierVehiculeDioRequest { 
    nouvelleImmatriculation: string;
    zoneJ1?: string;
    zoneF3?: number;
}

