/**
 * API (IDBATV7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageable-object';
import { AllEvenementDto } from './all-evenement-dto';
import { SortObject } from './sort-object';


export interface PageAllEvenementDto { 
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<AllEvenementDto>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
}

