/**
 * API (IDBATV7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageable-object';
import { SortObject } from './sort-object';
import { AllTypeApporteurDto } from './all-type-apporteur-dto';


export interface PageAllTypeApporteurDto { 
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<AllTypeApporteurDto>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
}

