/**
 * API (idbatv7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageable-object';
import { HistoriquePassageDio } from './historique-passage-dio';
import { SortObject } from './sort-object';


export interface PageHistoriquePassageDio { 
    totalElements?: number;
    totalPages?: number;
    pageable?: PageableObject;
    numberOfElements?: number;
    first?: boolean;
    last?: boolean;
    size?: number;
    content?: Array<HistoriquePassageDio>;
    number?: number;
    sort?: SortObject;
    empty?: boolean;
}

