/**
 * API (IDBATV7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageable-object';
import { AllUniteDesApportsDto } from './all-unite-des-apports-dto';
import { SortObject } from './sort-object';


export interface PageAllUniteDesApportsDto { 
    totalElements?: number;
    totalPages?: number;
    size?: number;
    content?: Array<AllUniteDesApportsDto>;
    number?: number;
    sort?: SortObject;
    first?: boolean;
    last?: boolean;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
}

