/**
 * API (idbatv7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PassageMatiereDio } from './passage-matiere-dio';


export interface PassageDio { 
    id: number;
    date: string;
    heure: string;
    nomSite: string;
    estDepotQualifie: boolean;
    matieres: Array<PassageMatiereDio>;
}

