/**
 * API (idbatv7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PassageRefuseDio { 
    id: number;
    date: string;
    heure: string;
    nomSite: string;
    commentaire?: string;
}

