/**
 * API (idbatv7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AchatPassagesHistoDio } from './achat-passages-histo-dio';


export interface PassagesInfoDio { 
    passagesRestants: number;
    achatsAnnee: Array<AchatPassagesHistoDio>;
    nbPassagesAchetesTotal: number;
    forfaitGratuitAnnuel: number;
    forfaitAcheteAnnuel: number;
    passagesConsommesAnnee: number;
}

