/**
 * API (IDBATV7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PutUsagerByIdRequest { 
    refClientIdBat?: number;
    titre?: string;
    nom?: string;
    prenom?: string;
    deuxiemeNom?: string;
    deuxiemePrenom?: string;
    raisonSociale?: string;
    siret?: string;
    telephone?: string;
    courriel: string;
    adresse?: string;
    complementAdresse?: string;
    deuxiemeComplementAdresse?: string;
    commentaire?: string;
    typesApporteurId: number;
    communeId: number;
}

