/**
 * API (IDBATV7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContratMatiereRequest } from './contrat-matiere-request';
import { ContratCommuneRequest } from './contrat-commune-request';
import { ContratEvenementRequest } from './contrat-evenement-request';
import { ContratTypeApporteurRequest } from './contrat-type-apporteur-request';
import { ContratMotifListeNoireRequest } from './contrat-motif-liste-noire-request';
import { ContratMoyenPaiementRequest } from './contrat-moyen-paiement-request';


export interface PutContratByIdRequest { 
    trigramme: string;
    nom: string;
    typesApporteurs: Array<ContratTypeApporteurRequest>;
    communes: Array<ContratCommuneRequest>;
    motifsListeNoires: Array<ContratMotifListeNoireRequest>;
    moyensPaiements: Array<ContratMoyenPaiementRequest>;
    matieres: Array<ContratMatiereRequest>;
    evenements: Array<ContratEvenementRequest>;
}

