/**
 * API (IDBATV7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SmartphoneDto { 
    id: number;
    numSerie?: string;
    nom: string;
    typeTerminal?: string;
    isSpare: boolean;
    isActif: boolean;
}

