/**
 * API (idbatv7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateProfilDioRequest { 
    nom?: string;
    prenom?: string;
    adresse?: string;
    telephone?: string;
    codePostal?: string;
    ville?: string;
}

