/**
 * API (idbatv7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehiculeDio } from './vehicule-dio';


export interface UsagerMeDio { 
    id: number;
    courriel: string;
    nom?: string;
    prenom?: string;
    telephone?: string;
    adresse?: string;
    codePostal?: string;
    ville?: string;
    hasChangedPassword: boolean;
    codeBarres?: string;
    numeroCarte?: string;
    vehicules: Array<VehiculeDio>;
    isPro: boolean;
}

