/**
 * API (idbatv7)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FichierDio } from './fichier-dio';


export interface VehiculeInscriptionDioRequest { 
    immatriculation: string;
    zoneJ1?: string;
    zoneF3?: number;
    carteGrise?: FichierDio;
}

